module.exports = [
  {
    languageOptions: {
      ecmaVersion: 2021,
      sourceType: 'script',
      globals: {
        p5: 'readonly',
        random: 'readonly',
        millis: 'readonly',
        noise: 'readonly',
        cos: 'readonly',
        sin: 'readonly',
        atan2: 'readonly',
        dist: 'readonly',
        createCanvas: 'readonly',
        color: 'readonly',
        width: 'readonly',
        height: 'readonly',
        PI: 'readonly',
        TWO_PI: 'readonly',
        HALF_PI: 'readonly',
        keyIsDown: 'readonly',
        UP_ARROW: 'readonly',
        DOWN_ARROW: 'readonly',
        LEFT_ARROW: 'readonly',
        RIGHT_ARROW: 'readonly',
        createVector: 'readonly',
        textFont: 'readonly',
        textAlign: 'readonly',
        CENTER: 'readonly',
        loadFont: 'readonly',
        text: 'readonly',
        rect: 'readonly',
        ellipse: 'readonly',
        line: 'readonly',
        stroke: 'readonly',
        fill: 'readonly',
        noStroke: 'readonly',
        strokeWeight: 'readonly',
        translate: 'readonly',
        rotate: 'readonly',
        push: 'readonly',
        pop: 'readonly',
        beginShape: 'readonly',
        vertex: 'readonly',
        endShape: 'readonly',
        abs: 'readonly',
        frameCount: 'readonly',
        randomSeed: 'readonly',
        noiseSeed: 'readonly',
        floor: 'readonly',
        ceil: 'readonly',
        round: 'readonly',
        loadImage: 'readonly',
        constrain: 'readonly',
      },
    },
    rules: {
      'no-unused-vars': 'warn',
    },
  },
];
